#!/bin/bash

DIR=$(pwd)

clear

error () { clear

read -p "

Input yang anda masukkan salah !

" input
	case $input in
		*) return
		;;
	esac
}

# Membuat file fstab
set-fstab () { clear

	read -p "

lanjut membuat file Fstab ? [Y/n] :

" yn

		case $yn in
			[Y/y]*) genfstab -U $DIR/fstab
			sudo mv $DIR/fstab /mnt/etc/fstab
			FN_FSTAB=$(ls -a /mnt/etc | grep fstab)
			if [ "$FN_FSTAB" = "fstab" ] ;
				then
					cat /mnt/etc/fstab
					read -p "

File fstab sudah berhasil dibuat ...

" ret
					case $ret in
						*) return
						;;
					esac
				else
					read -p "
File fstab gagal dibuat, silakan buat secara manual

" ret
					case $ret in
						*) return
						;;
					esac
			fi
			;;
			[N/n]*) return
			;;
			*) error
			;;
		esac
}

# Install base dan packages pendukung
set-base () { clear
	read -p "

Pilih salah satu kernel yang ingin di install,
Official Kernel : linux, linux-zen, linux-lts, linux-hardened,
linux-rt, linux-rt-lts

" kernel

	read -p "

Lanjut install $kernel dan Package pendukung [Y/n] :

" yn

		case $yn in
			[Yy]*) sudo pacstrap /mnt base base-devel $kernel linux-firmware intel-ucode reflector plymouth os-prober cups cups-pdf networkmanager vim ntfs-3g man-db ntp --overwrite "*"
			read -p "

Kernel dan packages pendukung sudah berhasil dibuat ...

" ret
			case $ret in
				*) return
				;;
			esac
			;;
			[Qq]*) return
			;;
			*) error
			;;
		esac
}

# Base Install Menu
echo "
################################################################################
##                   ARCH LINUX UTILITIES script by Reddof                    ##
################################################################################
##                               BASE INSTALL                                 ##
##                                                                            ##
##  1. Install Base Kernel dan Packages Pendukung                             ##
##  2. Membuat File Fstab                                                     ##
##  q. Kembali ke Menu Sebelumnya                                             ##
##                                                                            ##
##                                                                            ##
##                                                                            ##
##                                                                            ##
################################################################################
"

read -p "

Silakan masukkan pilihan anda :

" util
	case $util in
		1) set-base
		;;
		2) set-fstab
		;;
		[Qq]*) exit
		;;
		*) error
	esac

$DIR/sub/inst.d/./base-inst
