#!/bin/bash

DIR=$(pwd)
INST_DIR="$(pwd)/sub/inst.d"

clear

error () { clear

read -p "

Input yang anda masukkan salah !

" input
	case $input in
		*) return
		;;
	esac
}

# Restore settings dan files pribadi.
set-restore () { clear

read -p "

Ini adalah restore file pribadi saya ,lakukan ini  ? [Y/n] :

" yn

	case $yn in
		[Y/y]*) echo "

Mohon tunggu proses restore sedang berlangsung ...

"
		cp -R /home/Storage/Data/fonts/fonts /usr/share
		cp -R /home/Storage/Data/wallpapers/archlinux /usr/share/backgrounds
		fc-cache -fv
		;;
		[N/n]*) return
		;;
		*) error
		;;
	esac
}

# Setting pacman ke server lokal dengan reflector
set-reflector () { clear

read -p "

Setting repository ke server lokal.
Masukkan Nama negara misalnya Indonesia,
Atau kode negara misalnya ID untuk Indonesia :

" negara

read -p "

Apakah anda ingin set server ke negara $negara ? [Y/n] :

" yn

	case $yn in
		[Y/y]*) sudo reflector -p http,https --country $negara --latest 10 --fastest 5 --save /etc/pacman.d/mirrorlist
			echo "

Mohon tunggu sedang merubah server repository...
"
			sudo pacman -Sy archlinux-keyring --noconfirm --overwrite "*"
			read -p "

Berhasil merubah ke server lokal ...

" ret
			case $ret in
				*) return
				;;
			esac
		;;
		[N/n]*) return
		;;
		*) error
		;;
	esac

}

# Install menu
echo "
################################################################################
##                   ARCH LINUX UTILITIES script by Reddof                    ##
################################################################################
##                                 INSTALL                                    ##
##                                                                            ##
##  1. Setting Repository ke server Lokal                                     ##
##  2. Arch Install                                                           ##
##  3. Install Third Parties Packages                                         ##
##  4. Install Desktop Environment                                            ##
##  5. Restore Settings dan FIles Pribadi                                     ##
##  q. Kembali ke Menu Sebelumnya                                             ##
##                                                                            ##
################################################################################
"

read -p "

Silakan masukkan pilihan anda :

" util
	case $util in
		1) set-reflector
		;;
		2) $INST_DIR/./arch-install
		;;
		3) $INST_DIR/./third-inst
		;;
		4) $INST_DIR/./de-inst
		;;
		5) set-restore
		;;
		[Qq]*) exit
		;;
		*) error
		;;
	esac

$DIR/sub/./inst
